name: publish

on:
  push:
    tags:
      - "*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        python-version: "3.10"
        token: ${{ secrets.PAT }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        token: ${{ secrets.PAT }}
    - name: Run image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: "1.1.12"
        token: ${{ secrets.PAT }}
    - name: Build and publish
      env:
        # By default commits are created by hte github actions bot which can not trigger a new
        # workflow run. Using a PAT will allow the trigger for the publish job
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        poetry build
        poetry publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}